SPO coe_xfr_sql_profile_cruy5h2fpky94_1994943105.log;
SET ECHO ON TERM ON LIN 2000 TRIMS ON NUMF 99999999999999999999;
REM
REM $Header: 215187.1 coe_xfr_sql_profile_cruy5h2fpky94_1994943105.sql 11.4.3.5 2015/09/22 carlos.sierra $
REM
REM Copyright (c) 2000-2011, Oracle Corporation. All rights reserved.
REM
REM AUTHOR
REM   carlos.sierra@oracle.com
REM
REM SCRIPT
REM   coe_xfr_sql_profile_cruy5h2fpky94_1994943105.sql
REM
REM DESCRIPTION
REM   This script is generated by coe_xfr_sql_profile.sql
REM   It contains the SQL*Plus commands to create a custom
REM   SQL Profile for SQL_ID cruy5h2fpky94 based on plan hash
REM   value 1994943105.
REM   The custom SQL Profile to be created by this script
REM   will affect plans for SQL commands with signature
REM   matching the one for SQL Text below.
REM   Review SQL Text and adjust accordingly.
REM
REM PARAMETERS
REM   None.
REM
REM EXAMPLE
REM   SQL> START coe_xfr_sql_profile_cruy5h2fpky94_1994943105.sql;
REM
REM NOTES
REM   1. Should be run as SYSTEM or SYSDBA.
REM   2. User must have CREATE ANY SQL PROFILE privilege.
REM   3. SOURCE and TARGET systems can be the same or similar.
REM   4. To drop this custom SQL Profile after it has been created:
REM      EXEC DBMS_SQLTUNE.DROP_SQL_PROFILE('coe_cruy5h2fpky94_1994943105');
REM   5. Be aware that using DBMS_SQLTUNE requires a license
REM      for the Oracle Tuning Pack.
REM
WHENEVER SQLERROR EXIT SQL.SQLCODE;
REM
VAR signature NUMBER;
REM
DECLARE
sql_txt CLOB;
h       SYS.SQLPROF_ATTR;
BEGIN
sql_txt := q'[
SELECT DISTINCT
summaries.TRANSACTION_ITEM_SUMMARY_ID,
summaries.TXN_ID,
summaries.TXN_ITEM_ID,
summaries.MARKETPLACE_ID,
summaries.MERCHANT_CUSTOMER_ID,
summaries.STATE_NAME,
summaries.TYPE_NAME,
summaries.IS_ITEMIZED,
summaries.APPROVAL_STATUS_NAME,
summaries.TOTAL_AMOUNT,
summaries.CURRENCY_CODE,
summaries.TAM_CASE_ID,
summaries.REFERENCE_ID_TYPE,
summaries.REFERENCE_ID,
summaries.ORDER_ID,
to_char(summaries.REQUESTED_DATE,
'yyyy-mm-dd HH24:MI:SS')
as REQUESTED_DATE,
to_char(summaries.COMPLETED_DATE,
'yyyy-mm-dd HH24:MI:SS')
as COMPLETED_DATE,
to_char(summaries.APPROVAL_DATE,
'yyyy-mm-dd HH24:MI:SS')
as APPROVAL_DATE,
to_char(summaries.DECLINE_DATE,
'yyyy-mm-dd HH24:MI:SS')
as DECLINE_DATE,
to_char(summaries.REIMBURSED_DATE,
'yyyy-mm-dd HH24:MI:SS')
as REIMBURSED_DATE,
summaries.REQUESTED_BY,
summaries.APPROVED_BY,
summaries.DECLINED_BY,
(CASE action_reasons.ACTION_TYPE_NAME WHEN 'APPROVAL' THEN action_reasons.REASON ELSE '' END)
APPROVAL_REASON,
(CASE action_reasons.ACTION_TYPE_NAME WHEN 'DECLINE' THEN action_reasons.REASON ELSE '' END)
DECLINE_REASON,
(CASE action_reasons.ACTION_TYPE_NAME WHEN 'CANCELLATION' THEN action_reasons.REASON ELSE '' END)
CANCEL_REASON,
summaries.ITEM_FNSKU,
summaries.ITEM_MSKU,
summaries.ITEM_FC_ID,
summaries.ITEM_VALUATION_REASON,
summaries.ITEM_QUANTITY,
summaries.ITEM_REQUESTED_QUANTITY,
summaries.ITEM_FLIPPED_QUANTITY,
summaries.ITEM_UNIT_AMOUNT,
summaries.ITEM_SUBTOTAL,
summaries.CREATED_BY,
to_char(summaries.CREATION_DATE,
'yyyy-mm-dd HH24:MI:SS')
as CREATION_DATE,
summaries.LAST_UPDATED_BY,
to_char(summaries.LAST_UPDATED_DATE,
'yyyy-mm-dd HH24:MI:SS')
as LAST_UPDATED_DATE
FROM TXN_ITEM_SUMMARIES summaries
LEFT JOIN (
SELECT transaction_id,
action_type_name,
max(reason)
as reason
FROM TXN_ACTIONS
GROUP BY transaction_id,
action_type_name
)
action_reasons
ON summaries.txn_id = action_reasons.transaction_id
AND (
(summaries.approval_status_name = 'APPROVED' and action_reasons.action_type_name = 'APPROVAL' and summaries.state_name != 'CANCELED')
OR
(summaries.approval_status_name = 'DECLINED' and action_reasons.action_type_name = 'DECLINE' and summaries.state_name != 'CANCELED')
OR
(summaries.state_name = 'CANCELED' and action_reasons.action_type_name = 'CANCELLATION')
)
WHERE to_char(summaries.LAST_UPDATED_DATE,
'YYYY-MM-DD')
>= to_char(to_date('2015-09-17',
'YYYY-MM-DD')
- 3,
'YYYY-MM-DD')
]';
h := SYS.SQLPROF_ATTR(
q'[BEGIN_OUTLINE_DATA]',
q'[IGNORE_OPTIM_EMBEDDED_HINTS]',
q'[OPTIMIZER_FEATURES_ENABLE('11.2.0.3')]',
q'[DB_VERSION('11.2.0.3')]',
q'[OPT_PARAM('optimizer_index_cost_adj' 10)]',
q'[OPT_PARAM('optimizer_index_caching' 80)]',
q'[ALL_ROWS]',
q'[OUTLINE_LEAF(@"SEL$F5BB74E1")]',
q'[MERGE(@"SEL$2")]',
q'[OUTLINE_LEAF(@"SEL$37633EB5")]',
q'[MERGE(@"SEL$3")]',
q'[OUTLINE(@"SEL$1")]',
q'[OUTLINE(@"SEL$2")]',
q'[OUTLINE(@"SEL$4")]',
q'[OUTLINE(@"SEL$3")]',
q'[FULL(@"SEL$37633EB5" "SUMMARIES"@"SEL$3")]',
q'[NO_ACCESS(@"SEL$37633EB5" "from$_subquery$_005"@"SEL$3")]',
q'[LEADING(@"SEL$37633EB5" "SUMMARIES"@"SEL$3" "from$_subquery$_005"@"SEL$3")]',
q'[USE_NL(@"SEL$37633EB5" "from$_subquery$_005"@"SEL$3")]',
q'[USE_HASH_AGGREGATION(@"SEL$37633EB5")]',
q'[INDEX_RS_ASC(@"SEL$F5BB74E1" "TXN_ACTIONS"@"SEL$2" ("TXN_ACTIONS"."TRANSACTION_ID"))]',
q'[USE_HASH_AGGREGATION(@"SEL$F5BB74E1")]',
q'[END_OUTLINE_DATA]');
:signature := DBMS_SQLTUNE.SQLTEXT_TO_SIGNATURE(sql_txt);
DBMS_SQLTUNE.IMPORT_SQL_PROFILE (
sql_text    => sql_txt,
profile     => h,
name        => 'coe_cruy5h2fpky94_1994943105',
description => 'coe cruy5h2fpky94 1994943105 '||:signature||'',
category    => 'DEFAULT',
validate    => TRUE,
replace     => TRUE,
force_match => TRUE /* TRUE:FORCE (match even when different literals in SQL). FALSE:EXACT (similar to CURSOR_SHARING) */ );
END;
/
WHENEVER SQLERROR CONTINUE
SET ECHO OFF;
PRINT signature
PRO
PRO ... manual custom SQL Profile has been created
PRO
SET TERM ON ECHO OFF LIN 80 TRIMS OFF NUMF "";
SPO OFF;
PRO
PRO COE_XFR_SQL_PROFILE_cruy5h2fpky94_1994943105 completed
