set lines 400 pages 299
col SQL_EXEC_START for a27
col username for a27
SELECT INST_ID,
	 SID
	,SESSION_SERIAL#
	,SQL_ID
	,SQL_EXEC_ID
	,ELAPSED_TIME/1000000 ELAP_SEC
	,TO_CHAR(SQL_EXEC_START, 'YYYY-MM-DD-HH24:MI:SS') "SQL_EXEC_START"
	,SQL_PLAN_HASH_VALUE
	,USERNAME
	,STATUS
FROM GV$SQL_MONITOR
WHERE SQL_PLAN_HASH_VALUE=&phv
ORDER BY SQL_EXEC_START;